version: '3.8'

networks:
  dev-shared-network:
    external: true

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8g
        reservations:
          cpus: "1.0"
          memory: 4g
    volumes:
      - ../develop:/workspaces/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4000:4000"
    command: sleep infinity
    networks:
      - dev-shared-network
