networks:
  dev-shared-network:
    external: true

services:
  dev_java:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../develop:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ~/.ssh:/home/dev/.ssh:ro
    command: sleep infinity
    environment:
      - LANG=C.UTF-8
    user: ubuntu
    networks:
      - dev-shared-network
